### PR TITLE
Feature/cloudformation

### PR DESCRIPTION
**Pull request by pawel-lmcb**

### CODE REVIEW

**Comment by pawel-lmcb** [comment]
@rcampos87 let's also add:
An Instance pausing policy
A Savings Plan purchasing policy
A reserved instance purchasing policy
An EBS delete policy

I think that we should be good on that.

**Comment by pawel-lmcb** [comment]
@rcampos87 one change can we rename the IAM file to a single account?

So we have Single, Organizations, SubAccount. I think that breaks it down nicely.

**Comment by rcampos87** [comment]
@pawel-lmcb yes ill do that

**Comment by rcampos87** [comment]
@pawel-lmcb done

**Pull request merged**
