### PR TITLE
Add Tangoe white labeled version of onboarding scripts

### PR DESCRIPTION
**Pull request by ian-lmcb**
The tangoe scripts are live and publicly available in the `s3://tangoe-onboarding` bucket.

### CODE REVIEW

**Comment by ian-lmcb** [comment]
To see diff that tangoe made to our scripts look directly at commit [666eb97](https://github.com/lowermycloudbill/customer-support/pull/25/commits/666eb97a079c49659725eff04a0b9e6c8df06bac) and then also the v3 script I added and modified in commit [65dacc4](https://github.com/lowermycloudbill/customer-support/pull/25/commits/65dacc4667d475eef48d8d98422d4145db997728).

@rcampos87 Tangoe went ahead and rebranded our onboarding scripts to use the "Tangoe IaaS Optimization" feature name instead of "CloudAdmin" and they'll use an S3 bucket we created today to host these scripts `s3://tangoe-onboarding`. However, in their edits it looks like they used the older v2 version of the azure readonly script.

I see in #24 you added only the v3 readonly script to the repo.

Couple questions
1. Should we delete the older v2 readonly script from the tangoe bucket, in favor of the newer one, and let tangoe know? Presumably yes.
2. Should we delete the -cgi -new and -readonly variants of the azure scripts from our `s3://cloudadmin-onboarding` bucket (which is prob where they got confused and copied the wrong readonly script)? 

In this PR I have both the v2 script they edited and the v3 script which I modified to match. Note they removed the `.Read-only` from the app name. Not sure if they should be retaining that or if it doesn't matter really.

**Comment by rcampos87** [comment]
@ian-lmcb 
1. yes, we definitely need to delete v2 in favor of v3 and probably tell them to use v3 if they need to, heres the reason -- from my own tests in our azure account a custom role with no assignable roles is not added to the sub anymore.. i dunno if azure changed something on their CLI but it doesnt work anymore, so to fix that v3 uses the default Reader role which is basically samething and adds that to the role
2. perhaps for cgi its better just to remove the variants from the scripts as you said, although if i remember well... at the time when we sent the script to cgi, we didnt have those variants -- read only and full perms --, thats something i added later for us to have both options. (so maybe thats why the rename you noticed)

**Comment by rcampos87** [comment]
other thing we should definitely think about doing is pegging the CLI to a specific version... we run this script in the cloud storage so everytime a new cloud storage is created it has the latest CLI, so maybe we need to set it when starting up the script somehow. (last time i checked we didnt have anyway to)

**Comment by ian-lmcb** [comment]
Gotcha sounds good. I removed the v2 azure readonly script from here and from the s3 bucket.

Did a bit of searching but couldn't find any docs that would suggest there's a way to get a specific version of the azure CLI in the cloud shell.

**Pull request merged**
